name: football
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_inappwebview: ^5.7.2+3
  in_app_review:
  hive_flutter: ^1.1.0
  reorderable_grid_view: ^2.2.8
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/puzzle/image_1/
    - assets/images/puzzle/image_2/
    - assets/images/puzzle/image_3/
    - assets/images/puzzle/image_4/
    - assets/icons/
